version: 2.1
orbs:

  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
            - ~/home/circleci/.cache/Cypress
            - ~/.cache/Cypress
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn size
      
      - run: yarn test

      - run: yarn ci:cypress-run

      - run: yarn build